webtalk_init -webtalk_dir C:/EE2026_WS/S1_03_FDP/S1_03_FDP.sim/sim_1/behav/xsim/xsim.dir/decayingRoundTimerSimSrc_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Oct 24 01:27:03 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6c98dba6-3da3-4d50-95f9-b5f64702b9f3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7c613498ad7149f3bc61a711c7f31bf1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "37" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "13th Gen Intel(R) Core(TM) i7-1355U" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2611 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "100 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.26_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "11616_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2025003824 -regid "" -xml C:/EE2026_WS/S1_03_FDP/S1_03_FDP.sim/sim_1/behav/xsim/xsim.dir/decayingRoundTimerSimSrc_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/EE2026_WS/S1_03_FDP/S1_03_FDP.sim/sim_1/behav/xsim/xsim.dir/decayingRoundTimerSimSrc_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/EE2026_WS/S1_03_FDP/S1_03_FDP.sim/sim_1/behav/xsim/xsim.dir/decayingRoundTimerSimSrc_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
